version: '3'

volumes:
  portainer_data:

services:

  portainer:
    image: portainer/portainer
    restart: always
    command: --ssl --sslcert /certs/https.crt --sslkey /certs/https.key
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      - ./certs:/certs
