version: '3'

volumes:
  portainer_data:

services:

  portainer:
    image: portainer/portainer:1.16.2
    restart: always
    command: "--admin-password '$$2y$$05$$ax8adW5febFVXBHFaNWr1OnczpYvNvB664s1PrzyWqb/soThv/thS' -H unix:///var/run/docker.sock --ssl --sslcert /certs/https.crt --sslkey /certs/https.key"
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      - ./certs/portainer:/certs
